### ISSUE TITLE
첫 번째 issue입니다.

### ISSUE THREAD

**Issue by diversim90** [diversim90/myRemoteRepository#1]
첫 번째 issue입니다.
[first issue.txt](https://github.com/diversim90/myRemoteRepository/files/1087125/first.issue.txt)

**Comment by diversim80** [comment]
diversim80 : 첫 번재 issue를 확인했습니다.

**Comment by diversim90** [comment]
diversim80님이 확인했습니다.

**Comment by diversim90** [comment]
모든 구성원이 이슈를 확인했으므로, 이슈를 close합니다.
